#pragma once

enum Keys {
	TUSSAM_KEY_FAVORITES,
	TUSSAM_KEY_NEAR,
	TUSSAM_KEY_STOP_NAME,
	TUSSAM_KEY_STOP_NUMBER,
	TUSSAM_KEY_STOP_LINES,
	TUSSAM_KEY_STOP_FAVORITE,
	TUSSAM_KEY_REFRESH,
	TUSSAM_KEY_APPEND_STOP,
	TUSSAM_KEY_APPEND_LINE,
	TUSSAM_KEY_LINE_NUMBER,
	TUSSAM_KEY_BUS_1_TIME,
	TUSSAM_KEY_BUS_2_TIME,
	TUSSAM_KEY_ADD_FAVORITE,
	TUSSAM_KEY_REMOVE_FAVORITE,
	TUSSAM_KEY_NO_BUS_STOPS,
	TUSSAM_KEY_FETCH_STOP_DETAIL,
	TUSSAM_KEY_LAST_ITEM,
	AppKeyJSReady,
};
